version: '3'

networks:
  cass-local-network: #defining a network to connect to
    driver: bridge

services:
  cassandra:
    image: "cassandra" # use latest official cassandra version
    container_name: "cass-nodeA" # naming container for easier identification and shutdown
    networks:
      - cass-local-network
    ports:
      - '7000:7000'
      - '9042:9042' # Mapping ports
    volumes:
      - cassandra-data:/var/lib/cassandra/data/ # Setting up a volume so that data persists even if container shuts down
volumes:
  cassandra-data: # named volumes can be managed easier using docker-compose